###
POST http://localhost:4000/employee-api/employees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "mobileno": "1234567890",
  "designation": "Software Developer",
  "companyName": "Tech Corp"
}

###

GET http://localhost:4000/employee-api/employees

###

GET http://localhost:4000/employee-api/employees/69cb7e76caf9d729aea9f1bd

###

PUT http://localhost:4000/employee-api/employees/69cb7e76caf9d729aea9f1bd

Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com",
  "mobileno": "0987654321",
  "designation": "Senior Developer",
  "companyName": "Tech Corp"
}

###

DELETE http://localhost:4000/employee-api/employees/
